# Cat & Dog Classification using CNN

In [ ]:
#Load Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import warnings
warnings.filterwarnings('ignore')
import keras


In [ ]:
from keras.preprocessing.image import ImageDataGenerator
from keras.optimizers import Adam
from keras.callbacks import ModelCheckpoint
from keras.layers.normalization import BatchNormalization
from keras.regularizers import l2

### Load Data

In [ ]:
from zipfile import ZipFile
file_path='/content/drive/MyDrive/dataset.zip'
with ZipFile(file_path,'r') as zip:
  zip.extractall()
  print('finish')

finish


In [ ]:
train_data_path = '/content/dataset/training_set'
validation_data_path = '/content/dataset/test_set'

### Data Preprocessing

In [ ]:
training_datagen=ImageDataGenerator(rescale=1./255,
                                   rotation_range=40,
                                    width_shift_range=0.2,
                                      height_shift_range=0.2,
                                      shear_range=0.2,
                                      zoom_range=0.2,
                                      horizontal_flip=True,
                                      fill_mode='nearest')

In [ ]:
training_data=training_datagen.flow_from_directory(train_data_path,
                                                   target_size=(150, 150), 
                                      batch_size=32,
                                      class_mode='binary')

Found 8000 images belonging to 2 classes.


In [ ]:
training_data.class_indices

{'cats': 0, 'dogs': 1}

In [ ]:
valid_datagen = ImageDataGenerator(rescale=1./255)

In [ ]:
valid_data =  valid_datagen.flow_from_directory(validation_data_path, 
                                      target_size=(150, 150), 
                                      batch_size=32,
                                      class_mode='binary')

Found 2000 images belonging to 2 classes.


## Building CNN Model

In [ ]:
cnn_model=keras.models.Sequential([
                                   keras.layers.Conv2D(filters=32,kernel_size=3,input_shape=[150,150,3]),#Add First CNN Layer
                                   keras.layers.MaxPooling2D(pool_size=(2,2)), #Add First MaxPooling Layer

                                   keras.layers.Conv2D(filters=64,kernel_size=3),#Add Second CNN Layer
                                   keras.layers.MaxPooling2D(pool_size=(2,2)), #Add Second MaxPooling Layer

                                   keras.layers.Conv2D(filters=128,kernel_size=3),#Add Third CNN Layer
                                   keras.layers.MaxPooling2D(pool_size=(2,2)), #Add Third MaxPooling Layer

                                   keras.layers.Conv2D(filters=256,kernel_size=3),#Add Fourth CNN Layer
                                   keras.layers.MaxPooling2D(pool_size=(2,2)), #Add Fourth MaxPooling Layer

                                   keras.layers.Dropout(0.5),# Droupout Layers
                                   keras.layers.Flatten(),

                                   keras.layers.Dense(units=128,activation='relu'), # First Hidden Layer
                                   keras.layers.Dropout(0.1), # Droupout Layers

                                   keras.layers.Dense(units=256,activation='relu'), # Second Hidden Layer
                                   keras.layers.Dropout(0.25), # Droupout Layers

                                   keras.layers.Dense(units=2,activation='softmax') #Output Layer
                                   


])

In [ ]:
# compile cnn model
cnn_model.compile(optimizer = Adam(learning_rate=0.001), loss='sparse_categorical_crossentropy', metrics=['accuracy'])

## Train CNN Model

In [ ]:
model_path='/content/drive/MyDrive/Colab Notebooks/Cat & Dog Prediction/cat&dog_model.h5'
checkpoint=ModelCheckpoint(model_path,monitor='val_accuracy',verbose=1,save_best_only=True,mode='max')
callbacks_list=[checkpoint]

In [ ]:
history = cnn_model.fit(training_data, 
                          epochs=100, 
                          verbose=1, 
                          validation_data= valid_data,
                          callbacks=callbacks_list)

Epoch 1/100
250/250 [==============================] - 74s 271ms/step - loss: 0.7232 - accuracy: 0.5247 - val_loss: 0.6675 - val_accuracy: 0.5680

Epoch 00001: val_accuracy improved from -inf to 0.56800, saving model to /content/drive/MyDrive/Colab Notebooks/Cat & Dog Prediction/cat&dog_model.h5
Epoch 2/100
250/250 [==============================] - 65s 259ms/step - loss: 0.6751 - accuracy: 0.5875 - val_loss: 0.6947 - val_accuracy: 0.5760

Epoch 00002: val_accuracy improved from 0.56800 to 0.57600, saving model to /content/drive/MyDrive/Colab Notebooks/Cat & Dog Prediction/cat&dog_model.h5
Epoch 3/100
250/250 [==============================] - 63s 253ms/step - loss: 0.6621 - accuracy: 0.6035 - val_loss: 0.6374 - val_accuracy: 0.6680

Epoch 00003: val_accuracy improved from 0.57600 to 0.66800, saving model to /content/drive/MyDrive/Colab Notebooks/Cat & Dog Prediction/cat&dog_model.h5
Epoch 4/100
250/250 [==============================] - 64s 258ms/step - loss: 0.6506 - accuracy: 0.6220

### **Import Model**

In [ ]:
model_path='/content/drive/MyDrive/Colab Notebooks/Cat & Dog Prediction/cat&dog_model.h5'

In [ ]:
model=keras.models.load_model(model_path)

In [ ]:
# cat images
c1='/content/drive/MyDrive/Colab Notebooks/Cat & Dog Prediction/cat&dog test/cat/1.jpeg'
c2='/content/drive/MyDrive/Colab Notebooks/Cat & Dog Prediction/cat&dog test/cat/2.jpg'
c3='/content/drive/MyDrive/Colab Notebooks/Cat & Dog Prediction/cat&dog test/cat/3.png'
c4='/content/drive/MyDrive/Colab Notebooks/Cat & Dog Prediction/cat&dog test/cat/4.jpg'
c5='/content/drive/MyDrive/Colab Notebooks/Cat & Dog Prediction/cat&dog test/cat/5.jpg'

# Dog images
d1='/content/drive/MyDrive/Colab Notebooks/Cat & Dog Prediction/cat&dog test/dog/1.jpg'
d2='/content/drive/MyDrive/Colab Notebooks/Cat & Dog Prediction/cat&dog test/dog/2.jpg'
d3='/content/drive/MyDrive/Colab Notebooks/Cat & Dog Prediction/cat&dog test/dog/3.jpg'
d4='/content/drive/MyDrive/Colab Notebooks/Cat & Dog Prediction/cat&dog test/dog/4.jpg'
d5='/content/drive/MyDrive/Colab Notebooks/Cat & Dog Prediction/cat&dog test/dog/5.jpg'

In [ ]:
import numpy as np
from keras.preprocessing import image

In [ ]:
def pred_cat_dog(model, cat_or_dog):
  test_image = image.load_img(cat_or_dog, target_size = (150, 150))
  test_image = image.img_to_array(test_image)/255
  test_image = np.expand_dims(test_image, axis = 0)

  result = model.predict(test_image).round(3)

  pred = np.argmax(result)
  print(result, "--->>>", pred)

  if pred == 0:
    print('Predicted>>> Cat')
  else:
    print('Predicted>>> Dog')

## Predict Output

In [ ]:
for cat_or_dog in [c1,c2,c3,c4,c5,d1,d2,d3,d4,d5]:
  pred_cat_dog(model, cat_or_dog)

[[0.959 0.041]] --->>> 0
Predicted>>> Cat
[[1. 0.]] --->>> 0
Predicted>>> Cat
[[1. 0.]] --->>> 0
Predicted>>> Cat
[[0.98 0.02]] --->>> 0
Predicted>>> Cat
[[0.999 0.001]] --->>> 0
Predicted>>> Cat
[[0.013 0.987]] --->>> 1
Predicted>>> Dog
[[0.193 0.807]] --->>> 1
Predicted>>> Dog
[[0.014 0.986]] --->>> 1
Predicted>>> Dog
[[0.004 0.996]] --->>> 1
Predicted>>> Dog
[[0.027 0.973]] --->>> 1
Predicted>>> Dog
